In [1]:
import numpy as np


In [2]:
arr = np.arange(1e7)
larr = arr.tolist()

def list_time(alist, scalar):
    for i, val in enumerate(alist):
        alist[i] = val * scalar

    return alist

In [3]:
%timeit list_time(larr, 1.1)

2.08 s ± 76.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%timeit list_time(arr, 1.1)

7.85 s ± 986 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


####  创建数组

In [7]:
alist = [1, 2, 3]
arr = np.array(alist)
arr

array([1, 2, 3])

In [11]:
arr_10_30 = np.arange(10, 30)
arr_10_30

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [9]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [10]:
np.zeros(2, dtype=np.float32)

array([ 0.,  0.], dtype=float32)

In [13]:
arr_10_30.reshape(4,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [15]:
np.zeros((3,4)).shape

(3, 4)

####  记录数组